var searchData=
[
  ['pair_0',['Pair',['../a04034.html',1,'INVLIB']]],
  ['parksmcclellan_1',['ParksMcClellan',['../a03478.html',1,'UTILSLIB']]],
  ['partialdirectedcoherence_2',['PartialDirectedCoherence',['../a02714.html',1,'CONNLIB']]],
  ['peakfinderparams_3',['PeakFinderParams',['../a03482.html',1,'UTILSLIB']]],
  ['phaselagindex_4',['PhaseLagIndex',['../a02718.html',1,'CONNLIB']]],
  ['phaselockingvalue_5',['PhaseLockingValue',['../a02722.html',1,'CONNLIB']]],
  ['picardica_6',['PicardIca',['../a03486.html',1,'UTILSLIB']]],
  ['pickresult_7',['PickResult',['../a03114.html',1,'']]],
  ['plot_8',['Plot',['../a02790.html',1,'DISPLIB']]],
  ['processingsettings_9',['ProcessingSettings',['../a04442.html',1,'MNELIB']]],
  ['progressview_10',['ProgressView',['../a03034.html',1,'DISPLIB']]],
  ['projectorsview_11',['ProjectorsView',['../a03038.html',1,'DISPLIB']]],
  ['projectsettingsview_12',['ProjectSettingsView',['../a03042.html',1,'DISPLIB']]],
  ['pythonrunner_13',['PythonRunner',['../a04646.html',1,'UTILSLIB']]],
  ['pythonrunnerconfig_14',['PythonRunnerConfig',['../a04642.html',1,'UTILSLIB']]],
  ['pythonrunnerresult_15',['PythonRunnerResult',['../a04638.html',1,'UTILSLIB']]],
  ['pythontesthelper_16',['PythonTestHelper',['../a04650.html',1,'UTILSLIB']]]
];
